---
- hosts: test
  remote_user: vt250075
  vars: 
    output: []

  tasks:
    - name: get hostname
      command: uname -n
      changed_when: False
      register: hostname

    - name: get uptime
#      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      shell: /usr/bin/uptime
      changed_when: False
      register: uptime

    - debug: msg="{{output | to_nice_json}}"
    - local_action: copy content='{{output | to_nice_json}}' dest="/home/vt250075/uptime_linux_audit/audit.log"
