---
- hosts: test
  remote_user: vt250075
  vars: 
    - DATE: `date +"%m.%d.%y"`
    - LOGFIE: /home/vt250075/uptime_linux_audit/audit.$DATE.log

  tasks:
    - name: get hostname
      shell: uname -n >> $LOGFILE
      changed_when: False
      register: hostname

    - name: get uptime
#      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      shell: /usr/bin/uptime >> $LOGFILE
      changed_when: False
      register: uptime

    - debug: var={{ item }}
      with_items:
        - hostname.stdout
        - uptime.stdout
